#!/bin/bash

cd "$(dirname $0)/../../build"

export LANG=en_US.UTF-8
export PAWPAW_SKIP_LTO=1

function convert_path() {
    if [ -e jackd.exe ]; then
        echo "Z:\\$(echo ${@} | tr '/' '\\')"
    else
        echo ${@}
    fi
}

if [ -e mod-app.app ]; then
    DOCS_DIR=~/Documents
else
    DOCS_DIR=$(xdg-user-dir DOCUMENTS)
fi

if [ -e jackd.exe ]; then
    source ../PawPaw/local.env win64
    JACKD="wine jackd.exe"
    JACK_DRIVER="portaudio"
    JACK_DRIVER_DEVICE="ASIO::WineASIO Driver"
    JACK_DRIVER_OPTS=""
    JACK_SESSION="-C ./jack/jack-session.conf -X winmme"
    PATH_SEP=';'
elif [ -e mod-app.app ]; then
    source ../PawPaw/local.env macos-universal-10.15
    JACKD="./mod-app.app/Contents/MacOS/jackd"
    JACK_DRIVER="coreaudio"
    JACK_DRIVER_DEVICE="BuiltInSpeakerDevice"
    JACK_DRIVER_OPTS=""
    JACK_SESSION="-C ./mod-app.app/Contents/MacOS/jack/jack-session.conf -X coremidi"
    PATH_SEP=':'
    export DYLD_LIBRARY_PATH="${PAWPAW_PREFIX}/lib"
    export JACK_DRIVER_DIR="$(pwd)/mod-app.app/Contents/MacOS/jack"
else
    source ../PawPaw/local.env linux
    JACKD="./jackd"
    JACK_DRIVER="portaudio"
    JACK_DRIVER_DEVICE="ALSA::pulse"
    JACK_DRIVER_OPTS="-c 2"
    JACK_SESSION="-C ./jack/jack-session-alsamidi.conf"
    PATH_SEP=':'
    export LD_BIND_NOW=1
    export LD_LIBRARY_PATH="${PAWPAW_PREFIX}/lib"
    export JACK_DRIVER_DIR="$(pwd)/jack"
fi

if [ -e mod-app.app ]; then
    LV2_PATH="$(convert_path $(pwd)/mod-app.app/Contents/PlugIns/LV2)"
else
    LV2_PATH="$(convert_path $(pwd)/plugins)"
fi
LV2_PATH+="${PATH_SEP}$(convert_path ${DOCS_DIR}/MOD App/lv2)"
export LV2_PATH

export MOD_KEYS_PATH="$(convert_path ${DOCS_DIR}/MOD App/keys/)"

export JACK_NO_AUDIO_RESERVATION=1
export JACK_NO_START_SERVER=1

# export MOD_LOG=1
# export MOD_PLUGIN_THREAD_PRIORITY=57

# DEBUG="lldb --"

echo ${JACKD} -R -S -n mod-app ${JACK_SESSION} -d ${JACK_DRIVER} -d \"${JACK_DRIVER_DEVICE}\" ${JACK_DRIVER_OPTS} -r 48000 -p 256
exec ${DEBUG} ${JACKD} -R -S -n mod-app ${JACK_SESSION} -d ${JACK_DRIVER} -d "${JACK_DRIVER_DEVICE}" ${JACK_DRIVER_OPTS} -r 48000 -p 256
