#!/bin/bash

cd "$(dirname $0)/../../build"

export LANG=en_US.UTF-8
export PAWPAW_QUIET=1
export PAWPAW_SKIP_LTO=1

function convert_path() {
    if [ -e jackd.exe ]; then
        echo "Z:\\$(echo ${@} | tr '/' '\\')"
    else
        echo ${@}
    fi
}

if [ -e mod-desktop.app ]; then
    DOCS_DIR="${HOME}/Documents"
else
    DOCS_DIR="$(xdg-user-dir DOCUMENTS)"
fi

if [ -e jackd.exe ]; then
    source ../src/PawPaw/local.env win64
    JACKD="wine jackd.exe"
    if ! jack_wait -c | grep -q "not running"; then
        JACK_DRIVER="portaudio"
        JACK_DRIVER_OPTS="-d \"ASIO::WineASIO Driver\""
    else
        JACK_DRIVER="dummy"
        JACK_DRIVER_OPTS=""
    fi
    JACK_SESSION="-C ./jack/jack-session.conf -X winmme"
    PATH_SEP=';'
elif [ -e mod-desktop.app ]; then
    if [ "$(uname -m)" = "x86_64" ] && [ x"${1}" != x"macos-universal-10.15" ]; then
        source ../src/PawPaw/local.env macos-10.15
    else
        source ../src/PawPaw/local.env macos-universal-10.15
    fi
    JACKD="$(pwd)/mod-desktop.app/Contents/MacOS/jackd"
    JACK_DRIVER="coreaudio"
    JACK_DRIVER_OPTS="-P default"
    JACK_SESSION="-C ./mod-desktop.app/Contents/MacOS/jack/jack-session.conf -X coremidi"
    PATH_SEP=':'
    export DYLD_LIBRARY_PATH="${PAWPAW_PREFIX}/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
    export JACK_DRIVER_DIR="$(pwd)/mod-desktop.app/Contents/MacOS/jack"
else
    source ../src/PawPaw/local.env linux
    JACKD="$(pwd)/jackd"
    if ! jack_wait -c | grep -q "not running"; then
        JACK_DRIVER="portaudio"
        JACK_DRIVER_OPTS="-d JACK::system"
    else
        JACK_DRIVER="dummy"
        JACK_DRIVER_OPTS=""
    fi
    JACK_SESSION="-C ./jack/jack-session-alsamidi.conf"
    PATH_SEP=':'
    export LD_BIND_NOW=1
    export LD_LIBRARY_PATH="${PAWPAW_PREFIX}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    export JACK_DRIVER_DIR="$(pwd)/jack"
fi

LV2_PATH="$(convert_path "${DOCS_DIR}/MOD Desktop/lv2")"
if [ -e mod-desktop.app ]; then
    LV2_PATH+=":$(convert_path $(pwd)/mod-desktop.app/Contents/LV2)"
else
    LV2_PATH="${PATH_SEP}$(convert_path $(pwd)/plugins)"
fi
export LV2_PATH

export MOD_KEYS_PATH="$(convert_path "${DOCS_DIR}/MOD Desktop/keys/")"
export MOD_USER_FILES_DIR="$(convert_path "${DOCS_DIR}/MOD Desktop/user-files")"

export JACK_NO_START_SERVER=1

# export MOD_LOG=1
# export MOD_PLUGIN_THREAD_PRIORITY=57

mkdir -p "${DOCS_DIR}/MOD Desktop/keys"
mkdir -p "${DOCS_DIR}/MOD Desktop/user-files/Audio Recordings"

# DEBUG="lldb --"

echo ${JACKD} -R -S -n mod-desktop ${JACK_SESSION} -d ${JACK_DRIVER} ${JACK_DRIVER_OPTS} -r 48000 -p 256
exec ${DEBUG} ${JACKD} -R -S -n mod-desktop ${JACK_SESSION} -d ${JACK_DRIVER} ${JACK_DRIVER_OPTS} -r 48000 -p 256
