#!/bin/bash

cd "$(dirname $0)/../../build"

export LANG=en_US.UTF-8
export PAWPAW_SKIP_LTO=1

function convert_path() {
    if [ -e jackd.exe ]; then
        echo "Z:\\$(echo ${@} | tr '/' '\\')"
    else
        echo ${@}
    fi
}

if [ -e mod-ui.exe ]; then
    source ../PawPaw/local.env win64
    PATH_SEP=';'
else
    source ../PawPaw/local.env linux
    export LD_LIBRARY_PATH="$(pwd):${PAWPAW_PREFIX}/lib"
    PATH_SEP=':'
fi

DOCS_DIR=$(xdg-user-dir DOCUMENTS)
PYTHON="${EXE_WRAPPER} ${PAWPAW_PREFIX}/bin/python3${APP_EXT}"

export LV2_PATH="$(convert_path $(pwd)/plugins)${PATH_SEP}$(convert_path ${DOCS_DIR}/MOD App/lv2)"

export MOD_APP=1
export MOD_DEV_ENVIRONMENT=0
export MOD_DEVICE_HOST_PORT=18182
export MOD_DEVICE_WEBSERVER_PORT=18181
export MOD_KEYS_PATH="$(convert_path ${DOCS_DIR}/MOD App/keys)"
export MOD_USER_FILES_DIR="$(convert_path ${DOCS_DIR}/MOD App/user-files)"
export MOD_USER_PEDALBOARDS_DIR="$(convert_path ${DOCS_DIR}/MOD App/pedalboards)"
export MOD_USER_PLUGINS_DIR="$(convert_path ${DOCS_DIR}/MOD App/lv2)"
# export MOD_LOG=2

export JACK_NO_AUDIO_RESERVATION=1
export JACK_NO_START_SERVER=1

mkdir -p "${DOCS_DIR}/MOD App/user-files/Audio Loops"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Audio Recordings"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Audio Samples"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Audio Tracks"
mkdir -p "${DOCS_DIR}/MOD App/user-files/MIDI Clips"
mkdir -p "${DOCS_DIR}/MOD App/user-files/MIDI Songs"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Reverb IRs"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Speaker Cabinets IRs"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Hydrogen Drumkits"
mkdir -p "${DOCS_DIR}/MOD App/user-files/SF2 Instruments"
mkdir -p "${DOCS_DIR}/MOD App/user-files/SFZ Instruments"
mkdir -p "${DOCS_DIR}/MOD App/user-files/Aida DSP Models"
mkdir -p "${DOCS_DIR}/MOD App/user-files/NAM Models"

cd ../mod-ui

if [ -e ../build/mod-ui.exe ]; then
    rm -f utils/libjack64.dll
    ln -s $(realpath ../build/libjack64.dll) utils/libjack64.dll
fi

export MOD_DEFAULT_PEDALBOARD="$(convert_path $(pwd)/default.pedalboard)"
export MOD_HTML_DIR="$(convert_path $(pwd)/html)"

exec ${PYTHON} -c "from mod import webserver; webserver.run()"
